name: Lyre
options:
  bundleIdPrefix: com.lyre
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.40"
  createIntermediateGroups: true
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"

targets:
  Lyre:
    type: application
    platform: macOS
    sources:
      - path: Lyre
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lyre.app
        PRODUCT_NAME: Lyre
        MARKETING_VERSION: "1.5.2"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Lyre/Info.plist
        CODE_SIGN_ENTITLEMENTS: Lyre/Lyre.entitlements
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: true
        COMBINE_HIDPI_IMAGES: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
        SWIFT_STRICT_CONCURRENCY: complete

  LyreTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: LyreTests
    dependencies:
      - target: Lyre
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lyre.app.tests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Lyre.app/Contents/MacOS/Lyre"
        BUNDLE_LOADER: "$(TEST_HOST)"
